### ISSUE TITLE
throws exception for missing bucket

### ISSUE THREAD

**Issue by famesjranko** [2002Bishwajeet/no_signal#4]
I'm trying to run your app with appwrite, but it fails on the final part of create a user when trying to upload the profile image as there's no bucketId.

Exception has occurred.
AppwriteException (AppwriteException: Bucket not found (404))

I also tried using your collections creator script instead of doing it manually, and had same error thrown

**Comment by 2002Bishwajeet** [comment]
Hey @famesjranko , Thanks a lot for reporting this issue.  Actually this project was created using version 0.12.x and wasn't upgraded to it yet. And ofc it still worked on my machine even after updating to latest version thanks to appwrite migration script which already created a bucket for me.

But this Linked PR would fix this issue for you now.

Lemme know if you have any more doubts 😁

**Comment by famesjranko** [comment]
awesome, thanks for that!

I finally got past the no bucket exception, but also had to add read/write permissions for the bucket in Appwrite with "role:all"
