### ISSUE TITLE
providers/client.dart references missing utils/api.dart file

### ISSUE THREAD

**Issue by eg185060** [2002Bishwajeet/no_signal#6]
It seems a required file is missing.

providers.client.dart depends on `package:no_signal/utils/api.dart`

but that file is not in the `utils` folder, which has only
`setup_appwrite.dart`
`split_string.dart`

**Comment by 2002Bishwajeet** [comment]
Hey @eg185060 ,

You have to create this `api.dart` file storing all the necessary info.
I have mentioned in the [readme](https://github.com/2002Bishwajeet/no_signal/blob/master/README.md#setup-project-dashboard) as well

**Comment by eg185060** [comment]
Ah yeah i see now, sorry! My bad.
